server {
    listen 80;
    server_name localhost;
    root /var/www/html/pub;

    # --- 🔧 FIX  "upstream sent too big header" ---
    fastcgi_buffers 16 16k;
    fastcgi_buffer_size 32k;
    fastcgi_busy_buffers_size 32k;
    fastcgi_temp_file_write_size 32k;
    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;
    # --------------------------------------------------

    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass phpfpm:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    location /static/ {
        location ~ ^/static/version\d*/ {
            rewrite ^/static/(version\d*/)?(.*)$ /static/$2 last;
        }
        alias /var/www/html/pub/static/;
        add_header Cache-Control "public, max-age=31536000";
        access_log off;
        expires max;
    }

    location /media/ {
        root /var/www/html/pub/;
        try_files $uri $uri/ /get.php?$args;
        access_log off;
        add_header Cache-Control "public";
    }

    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|webp|woff2?)$ {
        expires max;
        add_header Pragma public;
        add_header Cache-Control "public, must-revalidate, proxy-revalidate";
    }
}
